site_name: Yelmo-docs
nav:
    - Home: index.md
    - Getting started: getting-started.md
    - Dependencies: dependencies.md
    - Parameters: parameters.md
    - Variables: yelmo-variables.md
    - Input/output: yelmo-io.md
    - Examples: example-programs.md
    - HPC notes: hpc-notes.md
    - Running with YelmoX: running-with-yelmox.md
#theme: mkdocs
theme:
    name: readthedocs

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

