site_name: Yelmo-docs
nav:
    - Home: index.md
    - Getting started: getting-started.md
    - Dependencies: dependencies.md
    - Parameters: parameters.md
    - Examples: example-programs.md
#theme: mkdocs
theme:
    name: readthedocs
